str = '-----python is good123@# ---'
len(str)
print(len(str))
print(str.upper())
print(str.lower())
print(str.swapcase())
print(str.capitalize())
print(str.title())
print(str.islower())
print(str.isupper())
print(str.istitle())
print(str.isdigit())
print(str.isalpha())
print(str.isalnum())
#true if all char in string is alpha num
print(str.strip('-'))
print(str.lstrip('-'))
print(str.rstrip('-'))
print(str.startswith('p'))
print(str.endswith('n'))
print(str.count('t'))
print(str.index('n'))
print(str.replace('p','P'))